### ISSUE TITLE
Can't identif BUG on MultiSeller (impo)

### ISSUE THREAD

**Issue by whGreg** [dmitryvhf/L2ScriptMaker#18]
![image](https://user-images.githubusercontent.com/52856410/73141564-8e9ac080-4096-11ea-9c7d-c4d28aabba63.png)

************** Текст исключения **************
System.InvalidCastException: Приведение строки "" к типу "Boolean" является недопустимым. ---> System.FormatException: Входная строка имела неверный формат.
   в Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   в Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(String Value)
   --- Конец трассировки внутреннего стека исключений ---
   в Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(String Value)
   в L2ScriptMaker.MultisellEditor.ButtonImport_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
************** Загруженные сборки **************

**Comment by dmitryvhf** [comment]
> ************** Текст исключения **************
> System.InvalidCastException: Приведение строки "" к типу "Boolean" является недопустимым. ---> System.FormatException: Входная строка имела неверный формат.
> в Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
> в Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(String Value)

Please provide more details.
What version of server scripts are you using? C4, C4 modified, etc?
What exactly you performed / clicked before this error appeared.

**Comment by dmitryvhf** [comment]
Thanks. Bug confirmed in both branches. I'll be fix it when as be possible.

**Comment by dmitryvhf** [comment]
Problem solved
