### ISSUE TITLE
(multisell Generator) no exist item 'sage's_stuff' in server script

### ISSUE THREAD

**Issue by adastmin1** [dmitryvhf/L2ScriptMaker#22]
no exist item 'sage's_stuff' in server script
![image](https://user-images.githubusercontent.com/60781118/74029435-c02c5980-49bd-11ea-9045-d9efb75e56d5.png)

**Comment by adastmin1** [comment]
AdvExt High Five

**Comment by dmitryvhf** [comment]
This is not bug. Your item into Import window is not exists.
Check it - "[_sage's_stuff_]" must be exist into "_item_pch.txt_".
