### ISSUE TITLE
(Reciple Generator )System.InvalidCastException: Приведение строки "" к типу "Integer" является недопустимым.

### ISSUE THREAD

**Issue by adastmin1** [dmitryvhf/L2ScriptMaker#23]
![image](https://user-images.githubusercontent.com/60781118/74030393-02569a80-49c0-11ea-8826-7e17e6812f26.png)

Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.InvalidCastException: Приведение строки "" к типу "Integer" является недопустимым. ---> System.FormatException: Входная строка имела неверный формат.
   в Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   в Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   --- Конец трассировки внутреннего стека исключений ---
   в Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   в L2ScriptMaker.RecipeGenerator.StartButton_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by dmitryvhf** [comment]
> System.InvalidCastException: Приведение строки "" к типу "Integer" является недопустимым. ---> System.FormatException: Входная строка имела неверный формат.

Possible wrong format for "item_pch.txt". Need file or details about file records.

**Comment by dmitryvhf** [comment]
Problem has not reproductive. Checked with recipe-e.txt (C6, C15).
